version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stockdog-db-backup"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16alhyd4wb12t"
s3_prefix = "stockdog-db-backup"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DatabaseHost=o677vxfi8ok6exrd.cbetxkdyhwsb.us-east-1.rds.amazonaws.com DatabaseName=ubkklfvaeg33j91i DatabaseUser=a6nss85wgo3zi43g DatabasePass=aasz2xg0u4k34np2 S3Bucket=stockdog-db-backup"
